/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.DatabaseConfig;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anam
 */
public class Mobil extends javax.swing.JPanel {

    /**
     * Creates new form Mobilpane
     */
    public Mobil() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen.width, screen.height);
        tampil_tb_mobil();
        data_combobox();
        id_otomatis();
    }
    private void id_otomatis(){
        try {
            Connection con = new DatabaseConfig().getConnection();
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM mobil order by id_mobil desc");
            if (rs.next()) {
                 String id = rs.getString("id_mobil").substring(1);
                 String AN = "" + (Integer.parseInt(id) + 1);
                 String nol = "";
                 if (AN.length() == 1) {
                    nol = "000";
                }else if(AN.length() == 2){
                     nol = "00";
                 }else if (AN.length() == 3) {
                     nol = "0";
                }else if (AN.length() == 4) {
                    nol = "";
                }
                 in_id.setText("M" + nol + AN);
            }else{
                in_id.setText("M0001");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void data_combobox(){
        cb_Status.removeAllItems();
        
//        cb_Status.addItem("Beroperasi");
        cb_Status.addItem("Tersedia");
    }
    
    private DefaultTableModel tabmode;
    
    private void tampil_tb_mobil(){
    Object []baris = {"Mobil", "Merk", "Tahun", "No Polisi", "No Rangka", "No Mesin", "Warna", "Jumlah Kursi", "Catatan", "Tarif", "Status"};
        tabmode = new DefaultTableModel (null, baris);
        tbl_mobil.setModel(tabmode);
        Connection con = new DatabaseConfig().getConnection();
        try {
            String sql = "SELECT * from mobil order by id_mobil asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String id_mobil = hasil.getString("id_mobil");
                String merk = hasil.getString("merk");
                String tahun = hasil.getString("tahun");
                String no_polisi = hasil.getString("no_polisi");
                String no_rangka = hasil.getString("no_rangka");
                String no_mesin = hasil.getString("no_mesin");
                String warna = hasil.getString("warna");
                String jumlah_kursi = hasil.getString("jumlah_kursi");
                String catatan = hasil.getString("catatan");
                String tarif = hasil.getString("tarif");
                String status = hasil.getString("status");
                String[] data = {id_mobil, merk, tahun, no_polisi, no_rangka, no_mesin, warna, jumlah_kursi, catatan, tarif, status};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
            JOptionPane.showMessageDialog(null, "Menampilkan data gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        in_warna = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        in_tahun = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        in_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        in_merk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mobil = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        in_tarif = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        in_jumlah_kursi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        in_norangka = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        in_nopolisi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RESET = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        SIMPAN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inCatatan = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        cb_Status = new javax.swing.JComboBox<>();
        in_nomesin = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        in_warna.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add(in_warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 261, 210, -1));

        jLabel14.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel14.setText("Warna");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 238, 100, -1));

        in_tahun.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add(in_tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 198, 210, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel6.setText("MOBIL");
        jLabel6.setToolTipText("");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 11, -1, -1));

        in_id.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        in_id.setEnabled(false);
        add(in_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 72, 210, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel3.setText("Id Mobil");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 49, 100, -1));

        in_merk.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add(in_merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 135, 210, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel4.setText("Merk Kendaraan");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, 100, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_mobil.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        tbl_mobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_mobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_mobil);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 315, 1090, 300));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel5.setText("Tahun");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, 100, -1));

        in_tarif.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add(in_tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 261, 210, -1));

        jLabel13.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel13.setText("Tarif Mobil");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 238, 100, -1));

        in_jumlah_kursi.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add(in_jumlah_kursi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 198, 210, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel9.setText("Jumlah Kursi");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 175, 100, -1));

        in_norangka.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add(in_norangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 135, 210, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel8.setText("No Rangka");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 112, 100, -1));

        in_nopolisi.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add(in_nopolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 72, 210, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel7.setText("No Polisi");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 49, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        RESET.setBackground(new java.awt.Color(51, 255, 51));
        RESET.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        HAPUS.setBackground(new java.awt.Color(255, 148, 148));
        HAPUS.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        EDIT.setBackground(new java.awt.Color(255, 255, 102));
        EDIT.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        EDIT.setText("EDIT");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        SIMPAN.setBackground(new java.awt.Color(117, 177, 250));
        SIMPAN.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel10.setText("Catatan");

        jLabel12.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel12.setText("No Mesin");

        inCatatan.setColumns(20);
        inCatatan.setRows(5);
        jScrollPane2.setViewportView(inCatatan);

        jLabel15.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel15.setText("Status");

        cb_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        in_nomesin.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(622, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(in_nomesin, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157)
                        .addComponent(SIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RESET, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EDIT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HAPUS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(in_nomesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        in_merk.setText("");
        in_tahun.setText("");
        in_nomesin.setText("");
        in_norangka.setText("");
        in_nopolisi.setText("");
        in_warna.setText("");
        in_jumlah_kursi.setText("");
        inCatatan.setText("");
        in_tarif.setText("");
        cb_Status.setSelectedIndex(0);
        id_otomatis();
    }
    private void klicktable(){
        int baris = tbl_mobil.getSelectedRow();
        in_id.setText((String)tbl_mobil.getValueAt(baris, 0));
        in_merk.setText((String)tbl_mobil.getValueAt(baris, 1));
        in_tahun.setText((String)tbl_mobil.getValueAt(baris, 2));
        in_nopolisi.setText((String)tbl_mobil.getValueAt(baris, 3));
        in_norangka.setText((String)tbl_mobil.getValueAt(baris, 4));
        in_nomesin.setText((String)tbl_mobil.getValueAt(baris, 5));
        in_warna.setText((String)tbl_mobil.getValueAt(baris, 6));
        in_jumlah_kursi.setText((String)tbl_mobil.getValueAt(baris, 7));
        inCatatan.setText((String)tbl_mobil.getValueAt(baris, 8));
        in_tarif.setText((String)tbl_mobil.getValueAt(baris, 9));
        cb_Status.setSelectedItem(tbl_mobil.getValueAt(baris, 10));
        // Mengembalikan nilai nopol untuk pengecekan apakah ada nopol yang sama nantinya.
//        String nopol = tbl_mobil.getValueAt(baris, 2).toString();
//        return nopol;
    }
    
    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        int  tahun, jumlah_kursi, tarif ;
        String id_mobil = "", merk="", no_polisi="", no_rangka="", no_mesin = "", warna = "", catatan = "", status="";
        id_mobil = in_id.getText();
        merk = in_merk.getText();
        tahun = Integer.parseInt(in_tahun.getText());
        no_polisi = in_nopolisi.getText();
        no_rangka = in_norangka.getText();
        no_mesin = in_nomesin.getText();
        warna = in_warna.getText();
        jumlah_kursi = Integer.parseInt(in_jumlah_kursi.getText());
        catatan = inCatatan.getText();
        tarif = Integer.parseInt(in_tarif.getText());
        status = cb_Status.getSelectedItem().toString();
        
        
        if (merk == "" || tahun == 0 || no_polisi == "" || no_rangka == "" || no_mesin == "" || warna == "" || jumlah_kursi == 0 || catatan == "" || status == "" || tarif == 0) {
            JOptionPane.showMessageDialog(null, "Silahkan isi semua form", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                Connection con = new DatabaseConfig().getConnection();
                String sql = "INSERT INTO mobil VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
                stat = con.prepareStatement(sql);
                stat.setString(1, id_mobil);
                stat.setString(2, merk);
                stat.setInt(3, tahun);
                stat.setString(4, no_polisi);
                stat.setString(5, no_rangka);
                stat.setString(6, no_mesin);
                stat.setString(7, warna);
                stat.setInt(8, jumlah_kursi);
                stat.setString(9, catatan);
                stat.setInt(10, tarif);
                stat.setString(11, status);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil di simpan", "informasi", JOptionPane.INFORMATION_MESSAGE);
    //            JOptionPane.showMessageDialog(null, "Isi status " + status, "informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_tb_mobil();
                reset();
                id_otomatis();
            } catch (Exception e) {
    //            System.out.println(no_bp + nama + tempat_lahir + jurusan + tanggal_lahir + tanggal_masuk);
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Menyimpan Data ga", "informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_SIMPANActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        // TODO add your handling code here:
        int baris = tbl_mobil.getSelectedRow();
        String id_mobil = tabmode.getValueAt(baris, 0).toString();
        String nopol = tabmode.getValueAt(baris, 2).toString();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin Menghapus data Mobil dengan id_mobil : " + id_mobil + "?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                Connection con = new DatabaseConfig().getConnection();
                String sql = "DELETE FROM mobil WHERE id_mobil = '"+id_mobil+"'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
//                tampil_tb_mahasiswa();
                reset();
                System.out.println(sql);
                tampil_tb_mobil();
                id_otomatis();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_HAPUSActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_RESETActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        // TODO add your handling code here:
        Connection con = new DatabaseConfig().getConnection();
        int  tahun, jumlah_kursi, tarif ;
        String id_mobil = "", merk="", no_polisi="", no_rangka="", no_mesin = "", warna = "", catatan = "", status="";
        id_mobil = in_id.getText();
        merk = in_merk.getText();
        tahun = Integer.parseInt(in_tahun.getText());
        no_polisi = in_nopolisi.getText();
        no_rangka = in_norangka.getText();
        no_mesin = in_nomesin.getText();
        warna = in_warna.getText();
        jumlah_kursi = Integer.parseInt(in_jumlah_kursi.getText());
        catatan = inCatatan.getText();
        tarif = Integer.parseInt(in_tarif.getText());
        status = cb_Status.getSelectedItem().toString();
        
        if (merk == "" || tahun == 0 || no_polisi == "" || no_rangka == "" || no_mesin == "" || warna == "" || jumlah_kursi == 0 || catatan == "" || status == "" || tarif == 0) {
            JOptionPane.showMessageDialog(null, "Silahkan isi semua form", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String sql = "UPDATE mobil SET merk=?, tahun=?, no_polisi=?,  no_rangka=?, no_mesin =?, warna =?, jumlah_kursi =?, catatan =?, tarif =?, status =?  WHERE id_mobil ='"+id_mobil+"'";
            PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, merk);
                stat.setInt(2, tahun);
                stat.setString(3, no_polisi);
                stat.setString(4, no_rangka);
                stat.setString(5, no_mesin);
                stat.setString(6, warna);
                stat.setInt(7, jumlah_kursi);
                stat.setString(8, catatan);
                stat.setInt(9, tarif);
                stat.setString(10, status);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
                tampil_tb_mobil();
                reset();
                id_otomatis();
                System.out.println(stat);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal di ubah");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_EDITActionPerformed

    private void tbl_mobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mobilMouseClicked
        // TODO add your handling code here:
        klicktable();
    }//GEN-LAST:event_tbl_mobilMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EDIT;
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton RESET;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JComboBox<String> cb_Status;
    private javax.swing.JTextArea inCatatan;
    private javax.swing.JTextField in_id;
    private javax.swing.JTextField in_jumlah_kursi;
    private javax.swing.JTextField in_merk;
    private javax.swing.JTextField in_nomesin;
    private javax.swing.JTextField in_nopolisi;
    private javax.swing.JTextField in_norangka;
    private javax.swing.JTextField in_tahun;
    private javax.swing.JTextField in_tarif;
    private javax.swing.JTextField in_warna;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_mobil;
    // End of variables declaration//GEN-END:variables
}
