/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.DatabaseConfig;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Anam
 */
public class MobilOwner extends javax.swing.JPanel {

    /**
     * Creates new form Mobilpane
     */
    public MobilOwner() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen.width, screen.height);
        tampil_tb_mobil("");
    }
    
    
    private DefaultTableModel tabmode;
    
    private void tampil_tb_mobil(String cari){
    Object []baris = {"Mobil", "Merk", "Tahun", "No Polisi", "No Rangka", "No Mesin", "Warna", "Jumlah Kursi", "Catatan", "Tarif", "Status"};
        tabmode = new DefaultTableModel (null, baris);
        tbl_mobil.setModel(tabmode);
        Connection con = new DatabaseConfig().getConnection();
        String sql;
        try {
           if(!cari.equals("")){
                sql = "SELECT * FROM mobil WHERE id_mobil LIKE '%"+cari+"%' "
                        + "OR merk LIKE '%"+cari+"%' "
                        + "OR tahun LIKE '%"+cari+"%' "
                        + "OR no_polisi LIKE '%"+cari+"%' "
                        + "OR warna LIKE '%"+cari+"%' "
                        + "OR status LIKE '%"+cari+"%' "
                        + "OR tarif LIKE '%"+cari+"%'";
            }else{
                sql = "SELECT * from mobil order by id_mobil asc";
            }
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String id_mobil = hasil.getString("id_mobil");
                String merk = hasil.getString("merk");
                String tahun = hasil.getString("tahun");
                String no_polisi = hasil.getString("no_polisi");
                String no_rangka = hasil.getString("no_rangka");
                String no_mesin = hasil.getString("no_mesin");
                String warna = hasil.getString("warna");
                String jumlah_kursi = hasil.getString("jumlah_kursi");
                String catatan = hasil.getString("catatan");
                String tarif = hasil.getString("tarif");
                String status = hasil.getString("status");
                String[] data = {id_mobil, merk, tahun, no_polisi, no_rangka, no_mesin, warna, jumlah_kursi, catatan, tarif, status};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
            JOptionPane.showMessageDialog(null, "Menampilkan data gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mobil = new javax.swing.JTable();
        in_cari = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CETAK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_mobil.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        tbl_mobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_mobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_mobil);

        in_cari.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        in_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                in_cariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                in_cariKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        jLabel19.setAlignmentY(0.0F);

        CETAK.setBackground(new java.awt.Color(51, 255, 51));
        CETAK.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        CETAK.setText("CETAK");
        CETAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CETAKActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CUSTOMER");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CETAK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(in_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(525, 525, 525)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CETAK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(in_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 640));
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void tbl_mobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mobilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_mobilMouseClicked

    private void in_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_cariKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_in_cariKeyPressed

    private void in_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_cariKeyReleased
        // TODO add your handling code here:
        String incari =  in_cari.getText();
        tampil_tb_mobil(incari);
    }//GEN-LAST:event_in_cariKeyReleased

    private void CETAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CETAKActionPerformed
        // TODO add your handling code here:

        JasperReport report;
        String path = ".\\src\\Report\\laporanMobil.jasper";
        try {
            report = (JasperReport) JRLoader.loadObjectFromFile(path);
            Connection con = new DatabaseConfig().getConnection();
            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
            
        } catch (Exception e) {
            System.out.println("Laporan Customer Eror: " + e);
        }
    }//GEN-LAST:event_CETAKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CETAK;
    private javax.swing.JTextField in_cari;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_mobil;
    // End of variables declaration//GEN-END:variables
}
