/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.DatabaseConfig;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anam
 */
public class Sopir extends javax.swing.JPanel {

    /**
     * Creates new form Sopir
     */
    public Sopir() {
        initComponents();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen.width, screen.height);
        tampil_tb_sopir();
        id_otomatis();
    }
    
    private void id_otomatis(){
        try {
            Connection con = new DatabaseConfig().getConnection();
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM sopir order by id_sopir desc");
            if (rs.next()) {
                 String id = rs.getString("id_sopir").substring(1);
                 String AN = "" + (Integer.parseInt(id) + 1);
                 String nol = "";
                 if (AN.length() == 1) {
                    nol = "000";
                }else if(AN.length() == 2){
                     nol = "00";
                 }else if (AN.length() == 3) {
                     nol = "0";
                }else if (AN.length() == 4) {
                    nol = "";
                }
                 in_id.setText("S" + nol + AN);
            }else{
                in_id.setText("S0001");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
//    
    
    private DefaultTableModel tabmode;
    
    public void tampil_tb_sopir(){
    Object []baris = {"Id Sopir","Wilayah Tujuan", "Tarif Sopir"};
        tabmode = new DefaultTableModel (null, baris);
        tbl_sopir.setModel(tabmode);
        Connection con = new DatabaseConfig().getConnection();
        try {
            String sql = "SELECT * from sopir order by id_sopir asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String id_sopir = hasil.getString("id_sopir");
                String wilayah_tujuan = hasil.getString("wilayah_tujuan");
                String tarif_sopir = hasil.getString("tarif_sopir");
                String[] data = {id_sopir,wilayah_tujuan, tarif_sopir};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
            JOptionPane.showMessageDialog(null, "Menampilkan data gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        in_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sopir = new javax.swing.JTable();
        in_wilayah_tujuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RESET = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        SIMPAN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        in_tarifsopir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        in_id.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        in_id.setEnabled(false);
        add(in_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 72, 210, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel3.setText("id_sopir");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 49, 100, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tbl_sopir.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        tbl_sopir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sopirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sopir);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 275, 1090, 340));

        in_wilayah_tujuan.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        add(in_wilayah_tujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 72, 210, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel7.setText("Wilayah Tujuan");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 49, 100, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        RESET.setBackground(new java.awt.Color(51, 255, 51));
        RESET.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        HAPUS.setBackground(new java.awt.Color(255, 148, 148));
        HAPUS.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        EDIT.setBackground(new java.awt.Color(255, 255, 102));
        EDIT.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        EDIT.setText("EDIT");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        SIMPAN.setBackground(new java.awt.Color(117, 177, 250));
        SIMPAN.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SOPIR");
        jLabel6.setToolTipText("");

        in_tarifsopir.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel8.setText("Tarif Sopir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(585, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RESET, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HAPUS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in_tarifsopir, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(194, 194, 194)
                                .addComponent(SIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EDIT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(497, 497, 497))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(in_tarifsopir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(394, 394, 394))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 640));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel4.setText("Wilayah Tujuan");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 49, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        in_wilayah_tujuan.setText("");
        in_tarifsopir.setText("");
        id_otomatis();
    }
    private void klicktable(){
        int baris = tbl_sopir.getSelectedRow();
        in_id.setText((String)tbl_sopir.getValueAt(baris, 0));
        in_wilayah_tujuan.setText((String)tbl_sopir.getValueAt(baris, 1));
        in_tarifsopir.setText((String)tbl_sopir.getValueAt(baris, 2));
    }
//    
    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        int  tarif ;
        String id_sopir = "", wilayah_tujuan ="";
        id_sopir = in_id.getText();
        wilayah_tujuan = in_wilayah_tujuan.getText();
        tarif = Integer.parseInt(in_tarifsopir.getText());
        
        if (wilayah_tujuan == "") {
            JOptionPane.showMessageDialog(null, "Silahkan isi seluruh form ", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(id_sopir == ""){
            JOptionPane.showMessageDialog(null, "Id sopir tidak ditemukan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else{
            try {
                Connection con = new DatabaseConfig().getConnection();
                String sql = "INSERT INTO sopir VALUES (?,?,?)";
                PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
                stat = con.prepareStatement(sql);
                stat.setString(1, id_sopir);
                stat.setString(2, wilayah_tujuan);
                stat.setInt(3, tarif);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil di simpan", "informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_tb_sopir();
                reset();
                id_otomatis();
            } catch (Exception e) {
    //            System.out.println(no_bp + nama + tempat_lahir + jurusan + tanggal_lahir + tanggal_masuk);
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Menyimpan Data gagal", "informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_SIMPANActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        // TODO add your handling code here:
        int baris = tbl_sopir.getSelectedRow();
        String id_sopir = tabmode.getValueAt(baris, 0).toString();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin Menghapus data Sopir dengan id : " + id_sopir + "?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                Connection con = new DatabaseConfig().getConnection();
                String sql = "DELETE FROM sopir WHERE id_sopir = '"+id_sopir+"'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
//                tampil_tb_mahasiswa();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                reset();
                System.out.println(sql);
                tampil_tb_sopir();
                id_otomatis();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_HAPUSActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_RESETActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        // TODO add your handling code here:
        Connection con = new DatabaseConfig().getConnection();
        int  tarif = 0;
        String id_sopir = "", wilayah_tujuan ="";
        id_sopir = in_id.getText();
        wilayah_tujuan = in_wilayah_tujuan.getText();
        tarif = Integer.parseInt(in_tarifsopir.getText());
        
        if (wilayah_tujuan == "") {
            JOptionPane.showMessageDialog(null, "Silahkan isi seluruh form ", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(id_sopir == ""){
            JOptionPane.showMessageDialog(null, "Id sopir tidak ditemukan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            String sql = "UPDATE sopir SET wilayah_tujuan=?, tarif_sopir=? WHERE id_sopir ='"+id_sopir+"'";
            PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, wilayah_tujuan);
                stat.setInt(2, tarif);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
                tampil_tb_sopir();
                reset();
                id_otomatis();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ubah data gagal");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_EDITActionPerformed

    private void tbl_sopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sopirMouseClicked
        // TODO add your handling code here:
        klicktable();
    }//GEN-LAST:event_tbl_sopirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EDIT;
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton RESET;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JTextField in_id;
    private javax.swing.JTextField in_tarifsopir;
    private javax.swing.JTextField in_wilayah_tujuan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_sopir;
    // End of variables declaration//GEN-END:variables
}
